services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    networks:
      - app-network
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always #コンテナを自動的に開始
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
      - ./db/init-script:/docker-entrypoint-initdb.d #起動時にSQLを実行する(volume作成済みであればSkip)
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
