services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always #コンテナを自動的に開始
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_data:/var/lib/postgresql/data
      - ./db/init-script:/docker-entrypoint-initdb.d #起動時にSQLを実行する(volume作成済みであればSkip)
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
